name: Build and distribute Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.22.0

      - name: Install additional dependencies on Windows (optional)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Check for pkgutil and install if necessary
        if: runner.os == 'macOS'
        run: |
          if ! command -v pkgutil &> /dev/null; then
            echo "pkgutil not found. Installing Xcode Command Line Tools..."
            xcode-select --install || true
            sudo xcode-select --switch /Library/Developer/CommandLineTools
          else
            echo "pkgutil is already installed"
          fi
          echo "pkgutil location: $(which pkgutil)"
          echo $PATH

      - name: Update PATH
        if: runner.os == 'macOS'
        run: |
          echo "/usr/sbin:/usr/bin:/sbin:/bin" >> $GITHUB_PATH

      - name: Build wheels
        env:
          CIBW_BUILD: cp311-*
        run: |
          cibuildwheel --output-dir dist --platform ${{ matrix.os == 'macos-latest' && 'macos' || matrix.os }}

      - name: Upload wheels to GitHub Releases (optional)
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*.whl

