name: Build and distribute Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.22.0

      - name: Build wheels
        env:
          CIBW_BUILD: cp311-*
          CIBW_ARCHS_WINDOWS: AMD64
        run: |
          cibuildwheel --output-dir dist

      - name: Upload Windows wheels
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheels-${{ github.sha }} # Make the name unique with commit ID
          path: dist/*.whl

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.22.0

      - name: Build wheels
        env:
          CIBW_BUILD: cp311-*
        run: |
          cibuildwheel --output-dir dist --platform linux

      - name: Upload Linux wheels
        uses: actions/upload-artifact@v3
        with:
          name: linux-wheels-${{ github.sha }} # Make the name unique with commit ID
          path: dist/*.whl

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.22.0

      - name: Build wheels
        env:
          CIBW_BUILD: cp311-*
          CIBW_ARCHS_MACOS: x86_64 arm64 # Specify architectures for macOS.
        run: |
          cibuildwheel --output-dir dist

      - name: Upload macOS wheels
        uses: actions/upload-artifact@v3
        with:
          name: macos-wheels-${{ github.sha }} # Make the name unique with commit ID
          path: dist/*.whl

  upload_to_testpypi:
    runs-on: ubuntu-latest
    needs: [build_windows, build_linux, build_macos] # Wait for all build jobs to complete.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download artifacts for Windows, Linux, and macOS.
      - name: Download Windows wheels
        uses: actions/download-artifact@v3
        with:
          name: windows-wheels-${{ github.sha }} # Download using commit ID.
          path: ./dist

      - name: Download Linux wheels
        uses: actions/download-artifact@v3
        with:
          name: linux-wheels-${{ github.sha }} # Download using commit ID.
          path: ./dist

      - name: Download macOS wheels
        uses: actions/download-artifact@v3
        with:
          name: macos-wheels-${{ github.sha }} # Download using commit ID.
          path: ./dist

      - name: Upload wheels to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1 # Correct action usage here.
        with:
          repository-url: https://test.pypi.org/legacy/ # Correct URL for uploading to TestPyPI.
          username: __token__ # Use __token__ for API token authentication.
          password: ${{ secrets.TEST_PYPI_API_TOKEN }} # Token stored in GitHub Secrets.
          packages-dir: dist # Directory containing all wheel files.
