name: Build and distribute Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.22.0

      - name: Build wheels
        env:
          CIBW_BUILD: cp311-*
          CIBW_ARCHS_WINDOWS: AMD64
        run: |
          cibuildwheel --output-dir dist

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheels
          path: dist/*.whl

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.22.0

      - name: Build wheels
        env:
          CIBW_BUILD: cp311-*
        run: |
          cibuildwheel --output-dir dist --platform linux

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: linux-wheels
          path: dist/*.whl
