name: Build and distribute Python package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest  # This defines the platform for the job (running on Ubuntu)
    strategy:
      matrix:
        python-version: [3.11]  # Specify the Python versions to use
        include:
          - os: ubuntu-latest  # Ubuntu platform for the build
          - os: windows-latest  # Windows platform for the build
          - os: macos-latest  # Use 'macos-latest' for cibuildwheel
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the source code using the latest version of the action
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Set up Node.js
        with:
          node-version: '20'  # Use Node.js version 20 by default
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}  # Set up Python using the version from the matrix
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install cibuildwheel  # Install cibuildwheel for building wheels
      - name: Install additional dependencies on Windows (optional)
        if: runner.os == 'Windows'  # Only run this step on Windows
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'  # Install CMake on Windows
      - name: Install Xcode Command Line Tools on macOS (optional)
        if: runner.os == 'macOS'
        run: |
          xcode-select --install  # Install Xcode command line tools
      - name: Install Homebrew and pkgutil dependencies on macOS (optional)
        if: runner.os == 'macOS'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  # Install Homebrew
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV  # Add Homebrew to PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install pkgutil  # Install pkgutil (Homebrew üzerinden)
      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist --platform ${{ matrix.os }}  # Build wheels for the specified platform
      - name: Upload wheels to GitHub Releases (optional)
        if: success() && github.event_name == 'push'  # Upload artifacts only on push events
        uses: actions/upload-artifact@v3
        with:
          name: wheels  # Name of the artifact to upload
          path: dist/*/.whl  # Upload all .whl files from the dist directory

