name: Upload to TestPyPI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/build_wheels.yml'  # Skip this workflow if changes are made to this file
      - 'dist/**'  # Skip this workflow if changes are made in the dist directory

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: your-artifact-name  # Specify the name of your artifact here
          path: ./dist               # Directory where the artifacts will be extracted

      - name: Unzip artifacts
        run: |
          unzip './dist/*.zip' -d ./dist  # Unzip the downloaded zip file

      - name: Upload wheels to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          username: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          packages-dir: dist
